### ISSUE TITLE
No .cabal file found 

### ISSUE THREAD

**Issue by yarax** [haskell-servant/example-servant-minimal#3]
During the installation
stack test --fast
No .cabal file found in directory /home/roman/sandbox/example-servant-minimal/

**Comment by soenkehahn** [comment]
Which version of `stack` are you using? This should work since `1.0.4`.

**Comment by yarax** [comment]
stack --version
Version 0.1.10.0 x86_64
But I've just installed it according to https://docs.haskellstack.org/en/stable/README/

**Comment by soenkehahn** [comment]
The current version is `1.2.0`.

Here's my guess what's going on: You had `stack` installed through your package manager (probably into `/usr/bin`). Then you installed `stack` according to the link you posted, which put the new executable into `~/.local/bin`. But that directory is not in your `PATH`. So when you're running `stack` from the command line it's still using the old `/usr/bin/stack` instead of the new `~/.local/bin/stack`. `which stack` should show you which executable is being used.

This is just a guess of course. Hope it helps.

**Comment by yarax** [comment]
```
curl -sSL https://get.haskellstack.org/ | sh
Stack Version 0.1.10.0 already appears to be installed at:
  /usr/bin/stack
Use 'stack upgrade' or your OS's package manager to upgrade.
which stack
/usr/bin/stack
```

Seems that https://get.haskellstack.org/ suggests 0.1 version

**Comment by soenkehahn** [comment]
It seems that it refused to install the current version of `stack`, because you already have an older version installed. Have you tried `stack upgrade`?

Pinging some stack developers in case they're interested: @mgsloan @borsboom (Hoping they don't mind.)

**Comment by soenkehahn** [comment]
@yarax: Did you finally figure this out? It's been some time, so I'll close this. Please reopen, if you're still interested in getting help with this.
